version: '3'
services:
  camera-stream:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /run/udev/:/run/udev:ro
      - /sys/kernel/debug:/sys/kernel/debug:ro
    devices:
      - /dev/video0:/dev/video0
      - /run/udev:/run/udev:ro
    privileged: true
    restart: "no"
    environment:
      - PYTHONUNBUFFERED=1
      - LIBCAMERA_LOG_LEVEL=3
